# Generated by Django 3.0.6 on 2020-08-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200803_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mem_nickname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
