# Generated by Django 3.0.6 on 2020-08-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='st_loc_longitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='str_loc_latitude',
            field=models.IntegerField(null=True),
        ),
    ]
