# Generated by Django 3.0.3 on 2020-08-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200810_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallcitycode', models.PositiveIntegerField(unique=True)),
                ('citycode', models.PositiveIntegerField(blank=True)),
                ('cityname', models.CharField(blank=True, max_length=100)),
                ('smallcityname', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
