# Generated by Django 3.0.3 on 2020-09-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_grade',
            field=models.FloatField(default=0),
        ),
    ]
