# Generated by Django 3.1.1 on 2020-11-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200905_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_top', models.ImageField(upload_to='images/')),
                ('simulation_slide', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
