# Generated by Django 3.0.3 on 2020-08-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200808_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='str_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
