# Generated by Django 3.0.3 on 2020-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200808_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='str_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='str_id',
        ),
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.AutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
